"""A client library for accessing strukcode

This package is generated by openapi-python-client.
A thin convenience wrapper `StrukCodeClient` is also provided.
"""

from .client import AuthenticatedClient, Client
from .extras import StrukCodeClient

__all__ = (
    "AuthenticatedClient",
    "Client",
    "StrukCodeClient",
)
