export namespace Flag {
  export const STRUKCODE_AUTO_SHARE = truthy("STRUKCODE_AUTO_SHARE")
  export const STRUKCODE_GIT_BASH_PATH = process.env["STRUKCODE_GIT_BASH_PATH"]
  export const STRUKCODE_CONFIG = process.env["STRUKCODE_CONFIG"]
  export const STRUKCODE_CONFIG_DIR = process.env["STRUKCODE_CONFIG_DIR"]
  export const STRUKCODE_CONFIG_CONTENT = process.env["STRUKCODE_CONFIG_CONTENT"]
  export const STRUKCODE_DISABLE_AUTOUPDATE = truthy("STRUKCODE_DISABLE_AUTOUPDATE")
  export const STRUKCODE_DISABLE_PRUNE = truthy("STRUKCODE_DISABLE_PRUNE")
  export const STRUKCODE_DISABLE_TERMINAL_TITLE = truthy("STRUKCODE_DISABLE_TERMINAL_TITLE")
  export const STRUKCODE_PERMISSION = process.env["STRUKCODE_PERMISSION"]
  export const STRUKCODE_DISABLE_DEFAULT_PLUGINS = truthy("STRUKCODE_DISABLE_DEFAULT_PLUGINS")
  export const STRUKCODE_DISABLE_LSP_DOWNLOAD = truthy("STRUKCODE_DISABLE_LSP_DOWNLOAD")
  export const STRUKCODE_ENABLE_EXPERIMENTAL_MODELS = truthy("STRUKCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const STRUKCODE_DISABLE_AUTOCOMPACT = truthy("STRUKCODE_DISABLE_AUTOCOMPACT")
  export const STRUKCODE_DISABLE_MODELS_FETCH = truthy("STRUKCODE_DISABLE_MODELS_FETCH")
  export const STRUKCODE_FAKE_VCS = process.env["STRUKCODE_FAKE_VCS"]
  export const STRUKCODE_CLIENT = process.env["STRUKCODE_CLIENT"] ?? "cli"

  // Experimental
  export const STRUKCODE_EXPERIMENTAL = truthy("STRUKCODE_EXPERIMENTAL")
  export const STRUKCODE_EXPERIMENTAL_FILEWATCHER = truthy("STRUKCODE_EXPERIMENTAL_FILEWATCHER")
  export const STRUKCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("STRUKCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const STRUKCODE_EXPERIMENTAL_ICON_DISCOVERY =
    STRUKCODE_EXPERIMENTAL || truthy("STRUKCODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const STRUKCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("STRUKCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const STRUKCODE_ENABLE_EXA =
    truthy("STRUKCODE_ENABLE_EXA") || STRUKCODE_EXPERIMENTAL || truthy("STRUKCODE_EXPERIMENTAL_EXA")
  export const STRUKCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("STRUKCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const STRUKCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("STRUKCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const STRUKCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("STRUKCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const STRUKCODE_EXPERIMENTAL_OXFMT = STRUKCODE_EXPERIMENTAL || truthy("STRUKCODE_EXPERIMENTAL_OXFMT")
  export const STRUKCODE_EXPERIMENTAL_LSP_TY = truthy("STRUKCODE_EXPERIMENTAL_LSP_TY")
  export const STRUKCODE_EXPERIMENTAL_LSP_TOOL = STRUKCODE_EXPERIMENTAL || truthy("STRUKCODE_EXPERIMENTAL_LSP_TOOL")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
