export namespace Flag {
  export const STRUKCODE_AUTO_SHARE = truthy("STRUKCODE_AUTO_SHARE")
  export const STRUKCODE_CONFIG = process.env["STRUKCODE_CONFIG"]
  export const STRUKCODE_CONFIG_DIR = process.env["STRUKCODE_CONFIG_DIR"]
  export const STRUKCODE_CONFIG_CONTENT = process.env["STRUKCODE_CONFIG_CONTENT"]
  export const STRUKCODE_DISABLE_AUTOUPDATE = truthy("STRUKCODE_DISABLE_AUTOUPDATE")
  export const STRUKCODE_DISABLE_PRUNE = truthy("STRUKCODE_DISABLE_PRUNE")
  export const STRUKCODE_PERMISSION = process.env["STRUKCODE_PERMISSION"]
  export const STRUKCODE_DISABLE_DEFAULT_PLUGINS = truthy("STRUKCODE_DISABLE_DEFAULT_PLUGINS")
  export const STRUKCODE_DISABLE_LSP_DOWNLOAD = truthy("STRUKCODE_DISABLE_LSP_DOWNLOAD")
  export const STRUKCODE_ENABLE_EXPERIMENTAL_MODELS = truthy("STRUKCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const STRUKCODE_DISABLE_AUTOCOMPACT = truthy("STRUKCODE_DISABLE_AUTOCOMPACT")
  export const STRUKCODE_FAKE_VCS = process.env["STRUKCODE_FAKE_VCS"]
  export const STRUKCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH =
    process.env["STRUKCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH"]

  // Experimental
  export const STRUKCODE_EXPERIMENTAL = truthy("STRUKCODE_EXPERIMENTAL")
  export const STRUKCODE_EXPERIMENTAL_WATCHER = STRUKCODE_EXPERIMENTAL || truthy("STRUKCODE_EXPERIMENTAL_WATCHER")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }
}
